- name: Install support packages
  action: "{{ ansible_facts.pkg_mgr }}"
  args:
    name: "{{ _pyenv_packages }}"
    state: present
  tags:
    - pyenv

- name: Clone pyenv repo
  git:
    repo: "{{ pyenv_repo_url }}"
    dest: "{{ pyenv_repo_dest }}"
  become_user: "{{ pyenv_user }}"
  tags:
    - pyenv

- name: Clone plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ pyenv_repo_dest }}/plugins/{{ item.name }}"
  become_user: "{{ pyenv_user }}"
  loop: "{{ pyenv_plugins }}"
  tags:
    - pyenv
