- name: Include distribution specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - pyenv

- include_tasks: "install-{{ _pyenv_install_method }}.yml"
  tags:
    - pyenv

- name: LINUX | Configure shell to use Pyenv
  lineinfile:
    state: present
    create: yes
    dest: "{{ _pyenv_shell[pyenv_shell | basename]['config_file'] }}"
    line: "{{ item }}"
    mode: '0644'
  loop: "{{ _pyenv_shell[pyenv_shell | basename]['lines'] }}"
  become_user: "{{ pyenv_user }}"
  tags:
    - pyenv
