- name: Include distribution specific variables
  include_vars: "{{ ansible_facts.os_family }}.yml"
  tags:
    - pyenv

- include_tasks: "install-{{ _pyenv_install_method }}.yml"
  tags:
    - pyenv

- name: Configure shell to use Pyenv
  lineinfile:
    state: present
    create: yes
    dest: "{{ _pyenv_shell[pyenv_shell | basename]['config_file'] }}"
    line: "{{ item }}"
    mode: '0644'
  loop: "{{ _pyenv_shell[pyenv_shell | basename]['lines'] }}"
  become: yes
  become_user: "{{ pyenv_user }}"
  tags:
    - pyenv

- name: Install Python versions using Pyenv
  command: "{{ pyenv_repo_dest }}/bin/pyenv install --skip-existing {{ item }}"
  become: yes
  become_user: "{{ pyenv_user }}"
  loop: "{{ pyenv_install_versions }}"
  register: result
  changed_when: "'Installed' in result.stdout"
  tags:
    - pyenv
