- name: Include distribution specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - pyenv

- include_tasks: "install-{{ _pyenv_install_method }}.yml"
  tags:
    - pyenv

- name: LINUX | Configure shell to use Pyenv
  lineinfile:
    state: present
    create: yes
    dest: "{{ _pyenv_shell[ansible_env.SHELL | basename]['config_file'] }}"
    line: "{{ item }}"
    mode: '0644'
  loop: "{{ _pyenv_shell[ansible_env.SHELL | basename]['lines'] }}"
  tags:
    - pyenv
