- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - yum:
        name: git
        state: present
      when: ansible_facts.pkg_mgr in ['yum', 'dnf']

    - apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_facts.pkg_mgr == 'apt'
